name: CI

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  examples_build_and_test:
    strategy:
      fail-fast: false
      matrix:
        example:
          [
            experimental/web-chat,
            experimental/noise-js,
            experimental/noise-rtc,
            experimental/relay-direct-rtc,
            experimental/rln-js,
            experimental/rln-identity,
            dogfooding,
            message-monitor,
            flush-notes,
            buddybook,
            keystore-management
          ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: install
        run: npm install
        working-directory: "examples/${{ matrix.example }}"

      - name: build
        run: |
          if [ "${{ matrix.example }}" == "buddybook" ]; then
            npm run build:ci
          else
            npm run build
          fi
        working-directory: "examples/${{ matrix.example }}"

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        working-directory: "examples/${{ matrix.example }}"
        if: matrix.example == 'dogfooding'

      - name: test
        run: npm run test --if-present
        working-directory: "examples/${{ matrix.example }}"
